# Generated by Django 4.2.30 on 2026-06-30 05:38

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pipelines', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SlackWebhook',
            fields=[
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('tenant_id', models.UUIDField(db_index=True, help_text='UUID of the tenant this record belongs to')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('webhook_url', models.URLField(max_length=2000)),
                ('channel_override', models.CharField(blank=True, default='', max_length=100)),
                ('display_name', models.CharField(blank=True, default='', max_length=255)),
                ('subscribed_events', models.JSONField(blank=True, default=list, help_text='List of activity_type values to notify on. Empty = all events.')),
                ('is_active', models.BooleanField(default=True)),
                ('last_triggered_at', models.DateTimeField(blank=True, null=True)),
                ('failure_count', models.IntegerField(default=0)),
                ('pipeline_filter', models.ForeignKey(blank=True, help_text='If set, only notify on deals in this pipeline', null=True, on_delete=django.db.models.deletion.SET_NULL, to='pipelines.pipeline')),
            ],
            options={
                'db_table': 'slack_webhook',
                'indexes': [models.Index(fields=['tenant_id', 'is_active'], name='slack_webho_tenant__ff5d92_idx')],
            },
        ),
    ]
