# Generated by Django 4.2.30 on 2026-06-28 19:07

import uuid

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="FileUpload",
            fields=[
                ("created_at", models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("tenant_id", models.UUIDField(db_index=True, help_text="UUID of the tenant this record belongs to")),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("original_filename", models.CharField(max_length=500)),
                ("file_key", models.CharField(help_text="S3 object key or storage path", max_length=1000)),
                ("file_size", models.BigIntegerField(default=0)),
                ("mime_type", models.CharField(blank=True, default="", max_length=100)),
                ("bucket", models.CharField(blank=True, default="", max_length=255)),
                ("entity_type", models.CharField(blank=True, db_index=True, default="", max_length=50)),
                ("entity_id", models.UUIDField(blank=True, db_index=True, null=True)),
                ("uploaded_by_id", models.UUIDField(blank=True, db_index=True, null=True)),
                ("is_temporary", models.BooleanField(default=False, help_text="Auto-cleanup after expiry")),
            ],
            options={
                "db_table": "files_upload",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["tenant_id", "entity_type", "entity_id"], name="files_uploa_tenant__58bbc7_idx"
                    ),
                    models.Index(fields=["tenant_id", "uploaded_by_id"], name="files_uploa_tenant__23a68d_idx"),
                ],
            },
        ),
    ]
