# Generated by Django 4.2.30 on 2026-06-28 19:07

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Tenant",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255)),
                ("subdomain", models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ("logo_url", models.URLField(blank=True, default="", max_length=500)),
                ("settings", models.JSONField(blank=True, default=dict)),
                ("max_users", models.IntegerField(default=50)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "teams_tenant",
                "indexes": [models.Index(fields=["subdomain"], name="teams_tenan_subdoma_09c009_idx")],
            },
        ),
        migrations.CreateModel(
            name="Team",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="teams", to="teams.tenant"
                    ),
                ),
            ],
            options={
                "db_table": "teams_team",
            },
        ),
        migrations.CreateModel(
            name="Role",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True, default="")),
                ("permissions", models.JSONField(blank=True, default=dict)),
                ("is_admin", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="roles", to="teams.tenant"
                    ),
                ),
            ],
            options={
                "db_table": "teams_role",
            },
        ),
        migrations.CreateModel(
            name="Membership",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("is_owner", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                ("joined_at", models.DateTimeField(auto_now_add=True)),
                (
                    "role",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="teams.role"
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="teams.team"
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="memberships", to="teams.tenant"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="memberships",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "teams_membership",
            },
        ),
        migrations.AddIndex(
            model_name="team",
            index=models.Index(fields=["tenant"], name="teams_team_tenant__b8e34a_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="team",
            unique_together={("tenant", "name")},
        ),
        migrations.AddIndex(
            model_name="role",
            index=models.Index(fields=["tenant"], name="teams_role_tenant__b9f433_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="role",
            unique_together={("tenant", "name")},
        ),
        migrations.AddIndex(
            model_name="membership",
            index=models.Index(fields=["tenant", "team"], name="teams_membe_tenant__339eee_idx"),
        ),
        migrations.AddIndex(
            model_name="membership",
            index=models.Index(fields=["user"], name="teams_membe_user_id_66d038_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="membership",
            unique_together={("user", "tenant")},
        ),
    ]
