# Generated by Django 4.2.30 on 2026-06-30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    """Add inherits_from FK to Role for role hierarchy."""

    dependencies = [
        ("teams", "0002_tenant_industry"),
    ]

    operations = [
        migrations.AddField(
            model_name="role",
            name="inherits_from",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="inheriting_roles",
                to="teams.role",
            ),
        ),
    ]
