# Generated by Django 5.2 on 2026-06-30 13:39

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomFieldDef',
            fields=[
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('tenant_id', models.UUIDField(db_index=True, help_text='UUID of the tenant this record belongs to')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
                ('field_type', models.CharField(choices=[('text', 'Text'), ('number', 'Number'), ('date', 'Date'), ('select', 'Select')], max_length=16)),
                ('entity_type', models.CharField(choices=[('contacts', 'Contacts'), ('deals', 'Deals'), ('accounts', 'Accounts')], max_length=16)),
                ('options', models.JSONField(blank=True, default=list, help_text='Options for select type')),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'core_custom_field_def',
                'ordering': ['entity_type', 'order', 'name'],
                'indexes': [models.Index(fields=['tenant_id', 'entity_type'], name='core_custom_tenant__67e130_idx')],
            },
        ),
    ]
