# Generated by Django 5.2 on 2026-06-30 13:41

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('tenant_id', models.UUIDField(db_index=True, help_text='UUID of the tenant this record belongs to')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('create', 'Created'), ('update', 'Updated'), ('delete', 'Deleted'), ('login', 'Login'), ('export', 'Export'), ('import', 'Import'), ('invite', 'Invited'), ('send', 'Sent'), ('archive', 'Archived'), ('restore', 'Restored'), ('other', 'Other')], db_index=True, max_length=20)),
                ('entity_type', models.CharField(db_index=True, help_text='e.g. contact, deal, account, note, email', max_length=50)),
                ('entity_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('entity_name', models.CharField(blank=True, default='', max_length=255)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Audit Log Entry',
                'verbose_name_plural': 'Audit Log Entries',
                'db_table': 'core_audit_log',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['tenant_id', 'entity_type', 'created_at'], name='core_audit__tenant__108ddb_idx'), models.Index(fields=['tenant_id', 'actor_id', 'created_at'], name='core_audit__tenant__cf9f78_idx')],
            },
        ),
    ]
