# Generated by Django 4.2.30 on 2026-06-28 19:07

import uuid

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Account",
            fields=[
                ("created_at", models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("tenant_id", models.UUIDField(db_index=True, help_text="UUID of the tenant this record belongs to")),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255)),
                ("domain", models.CharField(blank=True, default="", max_length=255)),
                ("industry", models.CharField(blank=True, default="", max_length=100)),
                ("description", models.TextField(blank=True, default="")),
                ("website", models.URLField(blank=True, default="", max_length=500)),
                ("phone", models.CharField(blank=True, default="", max_length=30)),
                ("address_line1", models.CharField(blank=True, default="", max_length=255)),
                ("address_line2", models.CharField(blank=True, default="", max_length=255)),
                ("city", models.CharField(blank=True, default="", max_length=100)),
                ("state", models.CharField(blank=True, default="", max_length=100)),
                ("postal_code", models.CharField(blank=True, default="", max_length=20)),
                ("country", models.CharField(blank=True, default="", max_length=100)),
                ("employees_count", models.IntegerField(blank=True, null=True)),
                ("annual_revenue", models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ("logo_url", models.URLField(blank=True, default="", max_length=500)),
                ("owner_id", models.UUIDField(blank=True, db_index=True, null=True)),
                ("tags", models.JSONField(blank=True, default=list)),
                ("custom_fields", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "db_table": "contacts_account",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Contact",
            fields=[
                ("created_at", models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("tenant_id", models.UUIDField(db_index=True, help_text="UUID of the tenant this record belongs to")),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                ("email", models.EmailField(blank=True, default="", max_length=255)),
                ("phone", models.CharField(blank=True, default="", max_length=30)),
                ("mobile", models.CharField(blank=True, default="", max_length=30)),
                ("job_title", models.CharField(blank=True, default="", max_length=200)),
                ("department", models.CharField(blank=True, default="", max_length=100)),
                ("avatar_url", models.URLField(blank=True, default="", max_length=500)),
                ("linkedin_url", models.URLField(blank=True, default="", max_length=500)),
                ("twitter_handle", models.CharField(blank=True, default="", max_length=100)),
                ("street", models.CharField(blank=True, default="", max_length=255)),
                ("city", models.CharField(blank=True, default="", max_length=100)),
                ("state", models.CharField(blank=True, default="", max_length=100)),
                ("postal_code", models.CharField(blank=True, default="", max_length=20)),
                ("country", models.CharField(blank=True, default="", max_length=100)),
                ("owner_id", models.UUIDField(blank=True, db_index=True, null=True)),
                ("source", models.CharField(blank=True, default="", max_length=50)),
                ("tags", models.JSONField(blank=True, default=list)),
                ("custom_fields", models.JSONField(blank=True, default=dict)),
                (
                    "account",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="contacts",
                        to="contacts.account",
                    ),
                ),
            ],
            options={
                "db_table": "contacts_contact",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="account",
            index=models.Index(fields=["tenant_id", "name"], name="contacts_ac_tenant__7dd029_idx"),
        ),
        migrations.AddIndex(
            model_name="account",
            index=models.Index(fields=["tenant_id", "domain"], name="contacts_ac_tenant__757487_idx"),
        ),
        migrations.AddIndex(
            model_name="account",
            index=models.Index(fields=["tenant_id", "industry"], name="contacts_ac_tenant__a00f41_idx"),
        ),
        migrations.AddIndex(
            model_name="contact",
            index=models.Index(fields=["tenant_id", "email"], name="contacts_co_tenant__c20f3a_idx"),
        ),
        migrations.AddIndex(
            model_name="contact",
            index=models.Index(fields=["tenant_id", "last_name", "first_name"], name="contacts_co_tenant__9ed7d7_idx"),
        ),
        migrations.AddIndex(
            model_name="contact",
            index=models.Index(fields=["tenant_id", "owner_id"], name="contacts_co_tenant__3e2f2f_idx"),
        ),
        migrations.AddIndex(
            model_name="contact",
            index=models.Index(fields=["tenant_id", "-created_at"], name="contacts_co_tenant__569a01_idx"),
        ),
    ]
