# Generated by Django 5.2 on 2026-06-30 13:48

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sync', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalendarWatchChannel',
            fields=[
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('tenant_id', models.UUIDField(db_index=True, help_text='UUID of the tenant this record belongs to')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('channel_id', models.CharField(max_length=255, unique=True)),
                ('resource_id', models.CharField(max_length=512)),
                ('resource_uri', models.CharField(blank=True, default='', max_length=1024)),
                ('webhook_url', models.CharField(max_length=1024)),
                ('expires_at', models.DateTimeField()),
                ('last_push_at', models.DateTimeField(blank=True, null=True)),
                ('last_message_number', models.BigIntegerField(blank=True, null=True)),
                ('state', models.CharField(choices=[('active', 'Active'), ('expired', 'Expired'), ('renewal_failed', 'Renewal Failed'), ('stopped', 'Stopped')], default='active', max_length=20)),
                ('error_message', models.TextField(blank=True, default='')),
                ('connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watch_channels', to='sync.syncconnection')),
            ],
            options={
                'db_table': 'sync_calendar_watch_channels',
                'indexes': [models.Index(fields=['channel_id'], name='sync_calend_channel_479b81_idx'), models.Index(fields=['state', 'expires_at'], name='sync_calend_state_4893cb_idx'), models.Index(fields=['connection'], name='sync_calend_connect_b99b50_idx')],
            },
        ),
    ]
