# Generated by Django 4.2.30 on 2026-06-28 19:07

import uuid

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="WebhookEndpoint",
            fields=[
                ("created_at", models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("tenant_id", models.UUIDField(db_index=True, help_text="UUID of the tenant this record belongs to")),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("url", models.URLField(max_length=2000)),
                ("secret", models.CharField(help_text="HMAC secret for signature verification", max_length=255)),
                ("events", models.JSONField(default=list, help_text="List of event types to subscribe to")),
                ("description", models.CharField(blank=True, default="", max_length=500)),
                ("is_active", models.BooleanField(default=True)),
                ("last_triggered_at", models.DateTimeField(blank=True, null=True)),
                ("failure_count", models.IntegerField(default=0)),
                ("max_retries", models.IntegerField(default=3)),
            ],
            options={
                "db_table": "webhooks_endpoint",
            },
        ),
        migrations.CreateModel(
            name="WebhookEvent",
            fields=[
                ("created_at", models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("tenant_id", models.UUIDField(db_index=True, help_text="UUID of the tenant this record belongs to")),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("event_type", models.CharField(max_length=100)),
                ("payload", models.JSONField(default=dict)),
                (
                    "status",
                    models.CharField(
                        choices=[("pending", "Pending"), ("delivered", "Delivered"), ("failed", "Failed")],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("attempt_count", models.IntegerField(default=0)),
                ("last_attempt_at", models.DateTimeField(blank=True, null=True)),
                ("next_retry_at", models.DateTimeField(blank=True, null=True)),
                ("response_status", models.IntegerField(blank=True, null=True)),
                ("response_body", models.TextField(blank=True, default="")),
                ("error_message", models.TextField(blank=True, default="")),
                (
                    "endpoint",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="deliveries",
                        to="webhooks.webhookendpoint",
                    ),
                ),
            ],
            options={
                "db_table": "webhooks_event",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="webhookendpoint",
            index=models.Index(fields=["tenant_id", "is_active"], name="webhooks_en_tenant__bee669_idx"),
        ),
        migrations.AddIndex(
            model_name="webhookevent",
            index=models.Index(fields=["status", "next_retry_at"], name="webhooks_ev_status_bc4bb1_idx"),
        ),
        migrations.AddIndex(
            model_name="webhookevent",
            index=models.Index(fields=["endpoint", "-created_at"], name="webhooks_ev_endpoin_9c7793_idx"),
        ),
    ]
