# Generated by Django 5.2 on 2026-06-30 13:47

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webhooks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebhookDeadEvent',
            fields=[
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('tenant_id', models.UUIDField(db_index=True, help_text='UUID of the tenant this record belongs to')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(max_length=100)),
                ('payload', models.JSONField(default=dict)),
                ('final_attempt_count', models.IntegerField()),
                ('last_error', models.TextField(blank=True, default='')),
                ('last_response_status', models.IntegerField(blank=True, null=True)),
                ('last_response_body', models.TextField(blank=True, default='')),
                ('failed_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolution_notes', models.TextField(blank=True, default='')),
                ('endpoint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dead_events', to='webhooks.webhookendpoint')),
                ('original_event', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dead_letter', to='webhooks.webhookevent')),
            ],
            options={
                'db_table': 'webhooks_dead_event',
                'ordering': ['-failed_at'],
                'indexes': [models.Index(fields=['endpoint', '-failed_at'], name='webhooks_de_endpoin_080c5a_idx'), models.Index(fields=['resolved_at'], name='webhooks_de_resolve_69e9fa_idx')],
            },
        ),
    ]
