# Generated by Django 4.2.30 on 2026-06-28 19:07

import uuid

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Note",
            fields=[
                ("created_at", models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("tenant_id", models.UUIDField(db_index=True, help_text="UUID of the tenant this record belongs to")),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("entity_type", models.CharField(db_index=True, max_length=50)),
                ("entity_id", models.UUIDField(db_index=True)),
                ("title", models.CharField(blank=True, default="", max_length=500)),
                ("content", models.TextField(blank=True, default="")),
                ("content_html", models.TextField(blank=True, default="")),
                ("is_pinned", models.BooleanField(default=False)),
                ("owner_id", models.UUIDField(blank=True, db_index=True, null=True)),
            ],
            options={
                "db_table": "notes_note",
                "ordering": ["-is_pinned", "-created_at"],
                "indexes": [
                    models.Index(
                        fields=["tenant_id", "entity_type", "entity_id", "-created_at"],
                        name="notes_note_tenant__fd18b6_idx",
                    ),
                    models.Index(fields=["tenant_id", "owner_id"], name="notes_note_tenant__d2c1fb_idx"),
                    models.Index(fields=["tenant_id", "is_pinned"], name="notes_note_tenant__802c3d_idx"),
                ],
            },
        ),
    ]
