# Generated by Django 5.2 on 2026-06-30 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='microsoft_access_token',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='user',
            name='microsoft_id',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='microsoft_refresh_token',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['microsoft_id'], name='accounts_us_microso_5ec733_idx'),
        ),
    ]
