# Generated by Django 5.2 on 2026-06-30 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_add_microsoft_oauth_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='recovery_codes',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='user',
            name='totp_created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='totp_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='totp_secret',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.CreateModel(
            name='SamlProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_id', models.UUIDField(db_index=True)),
                ('idp_entity_id', models.CharField(help_text='IdP Entity ID (issuer)', max_length=500)),
                ('idp_sso_url', models.URLField(help_text='IdP Single Sign-On URL (HTTP-Redirect binding)', max_length=500)),
                ('idp_slo_url', models.URLField(blank=True, default='', help_text='IdP Single Logout URL (optional)', max_length=500)),
                ('idp_x509_cert', models.TextField(help_text='IdP X.509 certificate (PEM format)')),
                ('attribute_mapping', models.JSONField(blank=True, default=dict, help_text='SAML attribute mapping. E.g. {"email": "email", "first_name": "firstName"}')),
                ('sp_entity_id', models.CharField(help_text='SP Entity ID (auto-generated)', max_length=500)),
                ('acs_url', models.URLField(help_text='Assertion Consumer Service URL (auto-generated)', max_length=500)),
                ('audience', models.URLField(blank=True, default='', help_text='Optional: restrict to a specific IdP audience', max_length=500)),
                ('default_role_id', models.UUIDField(blank=True, help_text='Role UUID assigned to JIT-provisioned users', null=True)),
                ('auto_create_users', models.BooleanField(default=True, help_text='Automatically create user accounts on SAML login from this IdP')),
                ('allowed_domains', models.JSONField(blank=True, default=list, help_text='Restrict SAML login to specific email domains. Empty list = allow any domain.')),
                ('is_active', models.BooleanField(default=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'accounts_saml_provider',
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('tenant_id',), name='uq_active_saml_provider_per_tenant')],
            },
        ),
    ]
