# Generated by Django 4.2.30 on 2026-06-28 19:07

import uuid

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="TaskItem",
            fields=[
                ("created_at", models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("tenant_id", models.UUIDField(db_index=True, help_text="UUID of the tenant this record belongs to")),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=500)),
                ("description", models.TextField(blank=True, default="")),
                (
                    "priority",
                    models.CharField(
                        choices=[("low", "Low"), ("medium", "Medium"), ("high", "High"), ("urgent", "Urgent")],
                        default="medium",
                        max_length=10,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("todo", "To Do"),
                            ("in_progress", "In Progress"),
                            ("done", "Done"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="todo",
                        max_length=20,
                    ),
                ),
                ("due_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("owner_id", models.UUIDField(blank=True, db_index=True, null=True)),
                ("assignee_id", models.UUIDField(blank=True, db_index=True, null=True)),
                ("entity_type", models.CharField(blank=True, db_index=True, default="", max_length=50)),
                ("entity_id", models.UUIDField(blank=True, db_index=True, null=True)),
            ],
            options={
                "db_table": "tasks_task",
                "ordering": ["-priority", "due_at", "-created_at"],
                "indexes": [
                    models.Index(fields=["tenant_id", "status"], name="tasks_task_tenant__6f5be3_idx"),
                    models.Index(fields=["tenant_id", "assignee_id"], name="tasks_task_tenant__05856a_idx"),
                    models.Index(fields=["tenant_id", "due_at"], name="tasks_task_tenant__07bd88_idx"),
                    models.Index(fields=["tenant_id", "priority", "due_at"], name="tasks_task_tenant__4cf0f9_idx"),
                ],
            },
        ),
    ]
