# Generated by Django 5.2 on 2026-06-30 13:53

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='APIKey',
            fields=[
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('tenant_id', models.UUIDField(db_index=True, help_text='UUID of the tenant this record belongs to')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text="Human-readable label e.g. 'CI Pipeline'", max_length=255)),
                ('key_prefix', models.CharField(editable=False, help_text='First 16 chars of the key for display/identification', max_length=16)),
                ('key_hash', models.CharField(editable=False, help_text='SHA-256 hash of the full API key', max_length=128, unique=True)),
                ('permissions', models.JSONField(blank=True, default=dict, help_text="Override permissions dict — merged on top of the user's role permissions. Leave empty to inherit all the user's role permissions.")),
                ('expires_at', models.DateTimeField(blank=True, help_text='If set, the key is rejected after this time', null=True)),
                ('last_used_at', models.DateTimeField(blank=True, help_text='Updated on every authenticated request (best-effort, throttled)', null=True)),
                ('last_ip_address', models.GenericIPAddressField(blank=True, help_text='IP address of the last request using this key', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('revoked_at', models.DateTimeField(blank=True, help_text='If set, the key was explicitly revoked', null=True)),
                ('user', models.ForeignKey(help_text='User who created/owns this key', on_delete=django.db.models.deletion.CASCADE, related_name='api_keys', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'apikeys_key',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['key_hash'], name='apikeys_key_key_has_f7584b_idx'), models.Index(fields=['tenant_id', 'is_active'], name='apikeys_key_tenant__1cd13d_idx'), models.Index(fields=['tenant_id', 'user'], name='apikeys_key_tenant__3a4964_idx'), models.Index(fields=['expires_at'], name='apikeys_key_expires_0472bd_idx')],
            },
        ),
    ]
