# Generated by Django 4.2.30 on 2026-06-28 19:07

import uuid

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="EmailMessage",
            fields=[
                ("created_at", models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("tenant_id", models.UUIDField(db_index=True, help_text="UUID of the tenant this record belongs to")),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("message_id", models.CharField(db_index=True, help_text="Gmail message ID", max_length=255)),
                ("thread_id", models.CharField(db_index=True, max_length=255)),
                (
                    "direction",
                    models.CharField(choices=[("inbound", "Inbound"), ("outbound", "Outbound")], max_length=10),
                ),
                ("from_email", models.EmailField(max_length=255)),
                ("to_emails", models.JSONField(default=list)),
                ("cc_emails", models.JSONField(blank=True, default=list)),
                ("bcc_emails", models.JSONField(blank=True, default=list)),
                ("subject", models.CharField(blank=True, default="", max_length=1000)),
                ("body_text", models.TextField(blank=True, default="")),
                ("body_html", models.TextField(blank=True, default="")),
                ("sent_at", models.DateTimeField()),
                ("received_at", models.DateTimeField(blank=True, null=True)),
                ("is_read", models.BooleanField(default=False)),
                ("is_starred", models.BooleanField(default=False)),
                ("labels", models.JSONField(blank=True, default=list)),
                ("entity_type", models.CharField(blank=True, db_index=True, default="", max_length=50)),
                ("entity_id", models.UUIDField(blank=True, db_index=True, null=True)),
                ("gmail_history_id", models.CharField(blank=True, default="", max_length=100)),
            ],
            options={
                "db_table": "email_messages",
                "ordering": ["-sent_at"],
                "indexes": [
                    models.Index(fields=["tenant_id", "thread_id", "-sent_at"], name="email_messa_tenant__e82984_idx"),
                    models.Index(fields=["tenant_id", "from_email"], name="email_messa_tenant__26700e_idx"),
                    models.Index(fields=["tenant_id", "-sent_at"], name="email_messa_tenant__2ae5c2_idx"),
                    models.Index(fields=["tenant_id", "message_id"], name="email_messa_tenant__6f3f30_idx"),
                ],
            },
        ),
    ]
