# Generated by Django 4.2.30 on 2026-06-29 16:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sync', '0001_initial'),
        ('contacts', '0001_initial'),
        ('pipelines', '0001_initial'),
        ('email', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailmessage',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emails_set', to='contacts.account'),
        ),
        migrations.AddField(
            model_name='emailmessage',
            name='connection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emails', to='sync.syncconnection'),
        ),
        migrations.AddField(
            model_name='emailmessage',
            name='contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emails_set', to='contacts.contact'),
        ),
        migrations.AddField(
            model_name='emailmessage',
            name='crm_thread',
            field=models.ForeignKey(blank=True, help_text='FK to CRM email_threads', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emails', to='sync.emailthread'),
        ),
        migrations.AddField(
            model_name='emailmessage',
            name='deal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emails_set', to='pipelines.deal'),
        ),
        migrations.AddField(
            model_name='emailmessage',
            name='error_message',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='emailmessage',
            name='external_id',
            field=models.CharField(blank=True, default='', help_text='Provider message ID for sent emails', max_length=512),
        ),
        migrations.AddField(
            model_name='emailmessage',
            name='external_thread_id',
            field=models.CharField(blank=True, default='', help_text="Provider's thread ID", max_length=512),
        ),
        migrations.AddField(
            model_name='emailmessage',
            name='from_name',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
        migrations.AddField(
            model_name='emailmessage',
            name='provider_labels',
            field=models.JSONField(blank=True, default=list, help_text='Gmail label IDs'),
        ),
        migrations.AddField(
            model_name='emailmessage',
            name='reply_to',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
        migrations.AddField(
            model_name='emailmessage',
            name='size_estimate',
            field=models.IntegerField(blank=True, help_text='Size in bytes', null=True),
        ),
        migrations.AddField(
            model_name='emailmessage',
            name='smtp_id',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
        migrations.AddField(
            model_name='emailmessage',
            name='snippet',
            field=models.CharField(blank=True, default='', max_length=512),
        ),
        migrations.AddField(
            model_name='emailmessage',
            name='status',
            field=models.CharField(choices=[('synced', 'Synced'), ('sending', 'Sending'), ('sent', 'Sent'), ('failed', 'Failed'), ('draft', 'Draft')], default='synced', max_length=10),
        ),
        migrations.AlterField(
            model_name='emailmessage',
            name='direction',
            field=models.CharField(choices=[('inbound', 'Inbound'), ('outbound', 'Outbound')], db_index=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='emailmessage',
            name='sent_at',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AddIndex(
            model_name='emailmessage',
            index=models.Index(fields=['tenant_id', 'direction', '-sent_at'], name='email_messa_tenant__1f63f2_idx'),
        ),
        migrations.AddIndex(
            model_name='emailmessage',
            index=models.Index(fields=['tenant_id', 'external_id'], name='email_messa_tenant__887f43_idx'),
        ),
    ]
