# Generated by Django 5.2 on 2026-06-30 13:48

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email', '0002_gmail_sync_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailTemplate',
            fields=[
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('tenant_id', models.UUIDField(db_index=True, help_text='UUID of the tenant this record belongs to')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('subject_template', models.CharField(max_length=1000)),
                ('body_html', models.TextField(blank=True, default='')),
                ('body_text', models.TextField(blank=True, default='', help_text='Plain text fallback. Auto-generated from HTML if empty.')),
                ('category', models.CharField(choices=[('general', 'General'), ('introduction', 'Introduction'), ('follow_up', 'Follow-up'), ('meeting', 'Meeting Confirmation'), ('proposal', 'Proposal'), ('thank_you', 'Thank You'), ('reminder', 'Reminder'), ('custom', 'Custom')], db_index=True, default='general', max_length=50)),
                ('is_shared', models.BooleanField(default=True, help_text='Shared with entire team vs. personal only')),
                ('variables_used', models.JSONField(blank=True, default=list, help_text='List of variable names found in subject_template / body_html / body_text')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='email_templates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Email Template',
                'verbose_name_plural': 'Email Templates',
                'db_table': 'email_templates',
                'ordering': ['-updated_at'],
                'indexes': [models.Index(fields=['tenant_id', 'category'], name='email_templ_tenant__6e5852_idx'), models.Index(fields=['tenant_id', 'created_by'], name='email_templ_tenant__450274_idx'), models.Index(fields=['tenant_id', '-updated_at'], name='email_templ_tenant__e10e18_idx')],
            },
        ),
    ]
