# Generated by Django 4.2.30 on 2026-06-28 19:07

import uuid

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Activity",
            fields=[
                ("created_at", models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("tenant_id", models.UUIDField(db_index=True, help_text="UUID of the tenant this record belongs to")),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (
                    "activity_type",
                    models.CharField(
                        choices=[
                            ("note", "Note"),
                            ("call", "Call"),
                            ("email", "Email"),
                            ("meeting", "Meeting"),
                            ("task", "Task"),
                            ("deal_stage_change", "Deal Stage Change"),
                            ("deal_status_change", "Deal Status Change"),
                            ("file_upload", "File Upload"),
                            ("system", "System"),
                        ],
                        max_length=30,
                    ),
                ),
                ("title", models.CharField(blank=True, default="", max_length=500)),
                ("description", models.TextField(blank=True, default="")),
                ("entity_type", models.CharField(db_index=True, max_length=50)),
                ("entity_id", models.UUIDField(db_index=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("actor_id", models.UUIDField(blank=True, db_index=True, null=True)),
                ("duration_minutes", models.IntegerField(blank=True, null=True)),
                ("call_outcome", models.CharField(blank=True, default="", max_length=100)),
                ("call_recording_url", models.URLField(blank=True, default="", max_length=500)),
            ],
            options={
                "db_table": "activities_activity",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["tenant_id", "entity_type", "entity_id", "-created_at"],
                        name="activities__tenant__3c63fc_idx",
                    ),
                    models.Index(fields=["tenant_id", "activity_type"], name="activities__tenant__9878d6_idx"),
                    models.Index(fields=["tenant_id", "actor_id"], name="activities__tenant__154b18_idx"),
                    models.Index(fields=["tenant_id", "-created_at"], name="activities__tenant__48ced4_idx"),
                ],
            },
        ),
    ]
