# Generated by Django 4.2.30 on 2026-06-29 16:08

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImportJob',
            fields=[
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('tenant_id', models.UUIDField(db_index=True, help_text='UUID of the tenant this record belongs to')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_by_id', models.UUIDField(db_index=True)),
                ('entity_type', models.CharField(choices=[('contact', 'Contact'), ('deal', 'Deal'), ('account', 'Account')], max_length=20)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('previewed', 'Previewed'), ('confirmed', 'Confirmed'), ('completed', 'Completed'), ('failed', 'Failed')], default='draft', max_length=20)),
                ('original_filename', models.CharField(max_length=500)),
                ('file_size', models.IntegerField(default=0)),
                ('detected_columns', models.JSONField(blank=True, default=list)),
                ('column_mapping', models.JSONField(blank=True, null=True)),
                ('dedup_key', models.CharField(blank=True, max_length=50, null=True)),
                ('file_content', models.TextField(blank=True, default='')),
                ('conflict_strategy', models.CharField(choices=[('skip', 'Skip existing'), ('update', 'Update existing'), ('overwrite', 'Overwrite existing')], default='skip', max_length=20)),
                ('preview', models.JSONField(blank=True, null=True)),
                ('summary', models.JSONField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, default='')),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'imports_importjob',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['tenant_id', '-created_at'], name='imports_imp_tenant__ecbaf5_idx'), models.Index(fields=['tenant_id', 'created_by_id'], name='imports_imp_tenant__167c2e_idx'), models.Index(fields=['tenant_id', 'entity_type', '-created_at'], name='imports_imp_tenant__643cef_idx'), models.Index(fields=['tenant_id', 'status'], name='imports_imp_tenant__1c990a_idx')],
            },
        ),
    ]
