# Generated by Django 4.2.30 on 2026-06-28 19:07

import uuid
from decimal import Decimal

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("contacts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Deal",
            fields=[
                ("created_at", models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("tenant_id", models.UUIDField(db_index=True, help_text="UUID of the tenant this record belongs to")),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255)),
                ("value", models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=15)),
                ("currency", models.CharField(default="USD", max_length=3)),
                (
                    "status",
                    models.CharField(
                        choices=[("open", "Open"), ("won", "Won"), ("lost", "Lost"), ("abandoned", "Abandoned")],
                        default="open",
                        max_length=20,
                    ),
                ),
                (
                    "probability",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Override win probability (0.00 - 1.00). If null, uses stage probability",
                        max_digits=5,
                        null=True,
                    ),
                ),
                ("expected_close_date", models.DateField(blank=True, null=True)),
                ("closed_at", models.DateTimeField(blank=True, null=True)),
                ("close_reason", models.CharField(blank=True, default="", max_length=255)),
                ("owner_id", models.UUIDField(blank=True, db_index=True, null=True)),
                ("description", models.TextField(blank=True, default="")),
                ("tags", models.JSONField(blank=True, default=list)),
                ("custom_fields", models.JSONField(blank=True, default=dict)),
                ("entered_stage_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "pipelines_deal",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Pipeline",
            fields=[
                ("created_at", models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("tenant_id", models.UUIDField(db_index=True, help_text="UUID of the tenant this record belongs to")),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, default="")),
                ("is_default", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "pipelines_pipeline",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Stage",
            fields=[
                ("created_at", models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("tenant_id", models.UUIDField(db_index=True, help_text="UUID of the tenant this record belongs to")),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255)),
                ("display_order", models.IntegerField(default=0)),
                (
                    "probability",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Win probability for deals in this stage (0.00 - 1.00)",
                        max_digits=5,
                    ),
                ),
                ("color", models.CharField(default="#6B7280", help_text="Hex color for the stage", max_length=7)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "pipeline",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="stages", to="pipelines.pipeline"
                    ),
                ),
            ],
            options={
                "db_table": "pipelines_stage",
                "ordering": ["display_order"],
            },
        ),
        migrations.AddIndex(
            model_name="pipeline",
            index=models.Index(fields=["tenant_id", "is_default"], name="pipelines_p_tenant__f80cc3_idx"),
        ),
        migrations.AddIndex(
            model_name="pipeline",
            index=models.Index(fields=["tenant_id", "-created_at"], name="pipelines_p_tenant__f95878_idx"),
        ),
        migrations.AddField(
            model_name="deal",
            name="account",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="deals",
                to="contacts.account",
            ),
        ),
        migrations.AddField(
            model_name="deal",
            name="contact",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="deals",
                to="contacts.contact",
            ),
        ),
        migrations.AddField(
            model_name="deal",
            name="pipeline",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="deals", to="pipelines.pipeline"
            ),
        ),
        migrations.AddField(
            model_name="deal",
            name="stage",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="deals", to="pipelines.stage"
            ),
        ),
        migrations.AddIndex(
            model_name="stage",
            index=models.Index(fields=["pipeline", "display_order"], name="pipelines_s_pipelin_792a4a_idx"),
        ),
        migrations.AddIndex(
            model_name="deal",
            index=models.Index(fields=["tenant_id", "status"], name="pipelines_d_tenant__39d4cf_idx"),
        ),
        migrations.AddIndex(
            model_name="deal",
            index=models.Index(fields=["tenant_id", "pipeline", "stage"], name="pipelines_d_tenant__dacc82_idx"),
        ),
        migrations.AddIndex(
            model_name="deal",
            index=models.Index(fields=["tenant_id", "owner_id"], name="pipelines_d_tenant__c1e6ca_idx"),
        ),
        migrations.AddIndex(
            model_name="deal",
            index=models.Index(fields=["tenant_id", "expected_close_date"], name="pipelines_d_tenant__0c8503_idx"),
        ),
        migrations.AddIndex(
            model_name="deal",
            index=models.Index(fields=["tenant_id", "-created_at"], name="pipelines_d_tenant__2278a3_idx"),
        ),
    ]
